linters:
  enable:
    - gosec
    - godot
    - misspell
    - stylecheck

run:
  go: "1.22"

linters-settings:
  stylecheck:
    checks: ["all","ST1*"]

issues:
  exclude-use-default: false

output:
  formats: colored-line-number
  
  # print lines of code with issue, default it true
  print-issued-lines: false

  # print linter name in the end of issue text, default it true
  print-linter-name: true